apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: simple-node
        image: omarzztelcocloud/simple-node
        ports:
        - containerPort: 8080
        args:
        - /bin/sh
        - -c
        - touch /health; echo "hello there" >> /health; sleep 500; rm -f /health; sleep 600
        livenessProbe:
          exec:
            command:
            - cat
            - /health
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 10
